upgrade to 47.1-1
deepin-community/gsettings-desktop-schemas pull request #2
Opened 2024-11-04 08:45 UTC by alphagocc

2024-11-04 08:45 UTC, alphagocc commented
/integrate

2024-11-04 08:49 UTC, alphagocc commented
/integrate

2024-11-04 09:03 UTC, alphagocc commented
/integrate

2024-11-15 06:58 UTC, UTsweetyfish requested changes

2024-11-15 06:58 UTC, UTsweetyfish commented on debian/deepin/OWNERS
这个文件不要删

2024-11-15 06:58 UTC, UTsweetyfish commented on debian/deepin/workflows.yml
这个文件不要删

2024-11-15 06:58 UTC, UTsweetyfish commented on debian/control
> +        metacity (<< 1:3.49),
```
$ apt policy metacity
metacity:
  Installed: (none)
  Candidate: 1:3.42.0-1
  Version table:
     1:3.42.0-1 500
        500 https://ci.deepin.com/repo/deepin/deepin-community/stable beige/main amd64 Packages
```

有不满足的 Breaks

2024-11-16 09:15 UTC, alphagocc commented on debian/control
> +        metacity (<< 1:3.49),
是要把所有的不满足的都一并升级上来吗

2024-12-17 10:47 UTC, closed without merging